---
name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
sort-direction: ascending

categories:
  - title: "🚨 Breaking changes"
    labels:
      - "breaking change"
  - title: "✨ New theme"
    labels:
      - "new theme"
  - title: "🐛 Bug fixes"
    labels:
      - "bugfix"
  - title: "🚀 Enhancements"
    labels:
      - "enhancement"
  - title: "📚 Documentation"
    labels:
      - "documentation"
  - title: "⬆️ Dependency updates"
    labels:
      - "dependencies"

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## What’s changed

  $CHANGES
